In [1]:
# Roberta attempt
# Anita Sun

In [22]:
import sqlite3
import pandas as pd

In [14]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
import torch
import tensorflow.keras as tf_keras

# Preprocess text (username and link placeholders)
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

# Tasks:
# emoji, emotion, hate, irony, offensive, sentiment
# stance/abortion, stance/atheism, stance/climate, stance/feminist, stance/hillary

task='emotion'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"

tokenizer = AutoTokenizer.from_pretrained(MODEL)

# download label mapping
mapping_link = f"https://raw.githubusercontent.com/cardiffnlp/tweeteval/main/datasets/{task}/mapping.txt"
with urllib.request.urlopen(mapping_link) as f:
    html = f.read().decode('utf-8').split("\n")
    csvreader = csv.reader(html, delimiter='\t')
labels = [row[1] for row in csvreader if len(row) > 1]

# PT
'''

model = AutoModelForSequenceClassification.from_pretrained(MODEL, trust_remote_code=True)
model.save_pretrained(MODEL)

text = "Celebrating my promotion 😎"
text = preprocess(text)
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
scores = output[0][0].detach().numpy()
scores = softmax(scores)


'''

# # TF
model = TFAutoModelForSequenceClassification.from_pretrained(MODEL)
model.save_pretrained(MODEL)

text = "Celebrating my promotion 😎"
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
scores = output[0][0].numpy()
scores = softmax(scores)

ranking = np.argsort(scores)
ranking = ranking[::-1]
for i in range(scores.shape[0]):
    l = labels[ranking[i]]
    s = scores[ranking[i]]
    print(f"{i+1}) {l} {np.round(float(s), 4)}")

tf_model.h5:   0%|          | 0.00/501M [00:00<?, ?B/s]

2025-02-27 12:45:21.449006: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

All the layers of TFRobertaForSequenceClassification were initialized from the model checkpoint at cardiffnlp/twitter-roberta-base-emotion.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFRobertaForSequenceClassification for predictions without further training.


1) joy 0.9382
2) optimism 0.0362
3) anger 0.0145
4) sadness 0.0112


In [23]:
conn = sqlite3.connect('raam_database.db', timeout=10)

In [24]:
cur = conn.cursor()

In [25]:
q = '''
    SELECT name FROM sqlite_master WHERE type="table"
    '''

cur.execute(q).fetchall()

[('health_anxiety_table_raw',),
 ('health_anxiety_posts',),
 ('sqlite_sequence',),
 ('health_anxiety_comments',),
 ('nursing_table_raw',),
 ('nursing_posts',),
 ('nursing_comments',),
 ('teaching_table_raw',),
 ('teaching_posts',),
 ('teaching_comments',)]

In [26]:
q2 = '''
    PRAGMA table_info(teaching_posts)
    '''

cur.execute(q2).fetchall()

[(0, 'post_id', 'INTEGER', 0, None, 1),
 (1, 'timestamp', 'TEXT', 0, None, 0),
 (2, 'username', 'TEXT', 0, None, 0),
 (3, 'post_title', 'TEXT', 0, None, 0),
 (4, 'post_body', 'TEXT', 0, None, 0),
 (5, 'score', 'TEXT', 0, None, 0),
 (6, 'comments_count', 'TEXT', 0, None, 0),
 (7, 'post_url', 'TEXT', 0, None, 0)]

In [44]:
q3 = '''
    SELECT post_body, post_id FROM teaching_posts
    
    '''

teaching_post_lst = cur.execute(q3).fetchall()

In [40]:
labels

['anger', 'joy', 'optimism', 'sadness']

In [59]:
df = pd.DataFrame({'post_id': [], 'body_text': [],
                   'anger': [], 'joy': [],
                   'optimism': [], 'sadness': []})

In [60]:
for weird_tup in teaching_post_lst:
    string = weird_tup[0]
    id = weird_tup[1]
    tokenized = tokenizer(string, return_tensors='tf')
    output = model(tokenized)
    scores = output[0][0].numpy()
    scores = softmax(scores)
    print(scores, labels)
    df.loc[len(df)] = [id, string, np.nan, np.nan, np.nan, np.nan]

    ranking = np.argsort(scores)
    ranking = ranking[::-1]
    print(string)

    df.loc[len(df)-1, labels] = scores

    for i in range(scores.shape[0]):
        l = labels[ranking[i]]
        s = scores[ranking[i]]
        #df.iloc[-1, l] = s
        print(f"{i+1}) {l} {np.round(float(s), 4)}")

[0.9187739  0.01099181 0.03515448 0.03507975] ['anger', 'joy', 'optimism', 'sadness']
Please let the door hit you on your big dumb head on the way out!
1) anger 0.9188
2) optimism 0.0352
3) sadness 0.0351
4) joy 0.011
[0.5995315  0.05724264 0.21298192 0.13024396] ['anger', 'joy', 'optimism', 'sadness']
Sorry but your kids are crazy because that's how they were raised, and we get to deal with that every day, thanks!
1) anger 0.5995
2) optimism 0.213
3) sadness 0.1302
4) joy 0.0572
[0.96682936 0.0066428  0.01227691 0.01425079] ['anger', 'joy', 'optimism', 'sadness']
Not a drill. I have a tool kit in my classroom. I passed out hammers and wrenches and screw drivers. I was a drill sergeant. YOU flip the table up against the door. YOU here pass out scissors. YOU grab that chair. 
The kids are freshmen in high school. They were ready to fight. We were ready to fight for an hour and a half while we waited in the dark. I cussed a lot. We had a couple giggles. I was absolutely terrified I would

InvalidArgumentError: Exception encountered when calling layer 'embeddings' (type TFRobertaEmbeddings).

{{function_node __wrapped__ResourceGather_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[0,512] = 514 is not in [0, 514) [Op:ResourceGather] name: 

Call arguments received by layer 'embeddings' (type TFRobertaEmbeddings):
  • input_ids=tf.Tensor(shape=(1, 682), dtype=int32)
  • position_ids=None
  • token_type_ids=tf.Tensor(shape=(1, 682), dtype=int32)
  • inputs_embeds=None
  • past_key_values_length=0
  • training=False

In [61]:
df.head()

post_id                                          body_text     anger  \
0        1  Please let the door hit you on your big dumb h...  0.918774   
1        2  Sorry but your kids are crazy because that's h...  0.599531   
2        3  Not a drill. I have a tool kit in my classroom...  0.966829   
3        4  We are currently remote with teachers required...  0.011842   
4        5  I teach SPED and we're in hybrid mode, so I ha...  0.034689   

        joy  optimism   sadness  
0  0.010992  0.035154  0.035080  
1  0.057243  0.212982  0.130244  
2  0.006643  0.012277  0.014251  
3  0.911455  0.050523  0.026180  
4  0.896975  0.035429  0.032907